void fg_black();
void fg_white();
void reset();
void bold();
void clear();
void underline();
void move_cursor(int, int);
void set_bg(int, int, int);
void bg_moves();
void dim();
void fg_gray();
void cursor_left();
void fg_red();
